
Parameters:
  ProjectName:
    Type: String
    MinLength: '1'
    MaxLength: '2048'
    Default: '-'

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - sit
      - qa 
      - prod
  VPCid:
    Type: String
    Default: vpc-03b6a6f63e6e2f60d
    AllowedValues:
      - vpc-0a4d1e63bd4c61a7f
      - vpc-03b6a6f63e6e2f60d

Resources:
  PrivateSubnetB: 
    Type: AWS::EC2::Subnet
    Properties: 
      # AssignIpv6AddressOnCreation: false
      CidrBlock: "10.10.11.0/24"
      # MapPublicIpOnLaunch: true
      # Tags: 
      #   - Name: "PrivateSubnetB"
      VpcId: !Ref VPCid
  


Outputs:
  PrivateSubnetA:
    Value: !Ref PrivateSubnetB #Fn::GetAtt: EC2ServerRole.Arn
    Description: Public Subnet B
    Export:
      Name: !Sub Private-Subnet-B-${Environment}-Arn
